### ISSUE TITLE
Getting edited image results

### ISSUE THREAD

**Issue by iampato** [weichengwu/wx_image_editor#1]
Using this example with the available API on this plugin

```dart
final ImagePicker picker = ImagePicker();
final XFile? photo = await picker.pickImage(
       source: ImageSource.camera,
 );
final res = await WxImageEditor.editImage(photo?.path ?? "");
```

How do I get the edited image since `res` is  boolean

**Comment by shuaihuzhou** [comment]
> Using this example with the available API on this plugin
> 
> ```dart
> final ImagePicker picker = ImagePicker();
> final XFile? photo = await picker.pickImage(
>        source: ImageSource.camera,
>  );
> final res = await WxImageEditor.editImage(photo?.path ?? "");
> ```
> 
> How do I get the edited image since `res` is boolean

tracing the code, I found the edited image path is the original path, but the edited image seems like no edited, It's strange

**Comment by weichengwu** [comment]
This plugin directly update the file at the path you passed in. The boolean result is for `isEdited`.

```dart
final path = ...; // the path of your picked image
final isEdited = await WxImageEditor.editImage(path);
if (!isEdited) {
    // means user clicked the cancel button.
    // sorry, it's not a good design.
    return;
}
```
